In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime
from konlpy.tag import Komoran
from konlpy.tag import Twitter
from konlpy.tag import Kkma
from konlpy.utils import pprint
twitter = Twitter()
komoran = Komoran()
kkma = Kkma()

%matplotlib inline

In [2]:
crawl = pd.read_csv("/Users/jinseokryu/newscrawling/newsCrawl.csv")

In [3]:
data = crawl.reindex(columns=['title','source','date','article'])

In [4]:
data.head()

title source      date  \
0              크레인 사고 6일 만에, 삼성중공업 일부 작업장 조업 재개   중앙일보  20170506   
1                   '성희롱 사건'에 대한 유담의 똑 부러지는 한마디   중앙일보  20170506   
2              이세돌 9단, 文 지지선언.."4년전 선거 복기 잘 한듯"   중앙일보  20170506   
3  유승민 "여론조사대로 결과 나오면 드라마 아냐..사표 걱정 말고 소신투표" 호소   중앙일보  20170506   
4           安 "최순실보다 더한 김현철 손 든 文..적폐 주장은 적반하장"   중앙일보  20170506   

                                             article  
0  크레인사고로 조업을 중단한 삼성중공업 거제조선소가 6일 일부 작업장에서 부분작업을 ...  
1   6일 유승민 바른정당 대선후보의 딸 유담씨가 최근 불거진 성희롱 사건과 관련해 "...  
2  이 9단은 "이번 더불어민주당 경선에 참가한 후보 모두를 좋아한다"며 "경선 당시 ...  
3  이곳 외에도 유 후보는 강남 가로수길, 서초 센트럴시티 등지에서 젊은층과 만나 "여...  
4  안철수 국민의당 대선후보가 6일 "최순실보다 더한 국정농단으로 나라를 어지럽힌 장본...

In [5]:
data.sort_values(by='date',ascending=True,inplace=True)

In [6]:
date_converter=lambda x: datetime.strptime(str(x),"%Y%m%d")
data['date']=data['date'].apply(date_converter)
data.head()

title source       date  \
33          [통계뉴스]문재인 앞서고 안철수-홍준표 혼전 양상   동아일보 2017-05-01   
25        '민주정책통합포럼' 선대위 편제..상임위원장에 조대엽   중앙일보 2017-05-01   
146       安, 민주노총 반발로 전태일 동상 앞 헌화 행사 취소   조선일보 2017-05-01   
27    "바른정당 의원 14명, 자유한국당 합류"..홍준표 지지할듯   중앙일보 2017-05-01   
28   [쓸·정] 대선 재외투표율 '역대 최다'가 우리에게 주는 의미   중앙일보 2017-05-01   

                                               article  
33   지난주 대선후보 여론조사에서는 더불어민주당 문재인 후보와 국민의당 안철수 후보의 평...  
25   민주정책통합포럼은 문 후보의 싱크탱크인 ‘정책공간 국민성장’을 기반으로 민주당 경선...  
146  안철수 국민의당 대선후보가 근로자의 날인 1일 서울 청계천 전태일 동상 앞에서  ‘...  
27   바른정당 소속의원 14명이 자유한국당에 합류한다는 언론 보도가 나왔다. ,1일 이데...  
28   제19대 대통령 선거 재외국민 투표가 30일(현지 시간)자로 종료됐습니다. 이번 재...

In [7]:
data['source'].value_counts()

중앙일보    120
조선일보    120
동아일보    111
Name: source, dtype: int64

In [8]:
data.set_index(['date','source']).head()

title  \
date       source                                       
2017-05-01 동아일보           [통계뉴스]문재인 앞서고 안철수-홍준표 혼전 양상   
           중앙일보         '민주정책통합포럼' 선대위 편제..상임위원장에 조대엽   
           조선일보         安, 민주노총 반발로 전태일 동상 앞 헌화 행사 취소   
           중앙일보     "바른정당 의원 14명, 자유한국당 합류"..홍준표 지지할듯   
           중앙일보    [쓸·정] 대선 재외투표율 '역대 최다'가 우리에게 주는 의미   

                                                             article  
date       source                                                     
2017-05-01 동아일보    지난주 대선후보 여론조사에서는 더불어민주당 문재인 후보와 국민의당 안철수 후보의 평...  
           중앙일보    민주정책통합포럼은 문 후보의 싱크탱크인 ‘정책공간 국민성장’을 기반으로 민주당 경선...  
           조선일보    안철수 국민의당 대선후보가 근로자의 날인 1일 서울 청계천 전태일 동상 앞에서  ‘...  
           중앙일보    바른정당 소속의원 14명이 자유한국당에 합류한다는 언론 보도가 나왔다. ,1일 이데...  
           중앙일보    제19대 대통령 선거 재외국민 투표가 30일(현지 시간)자로 종료됐습니다. 이번 재...

In [9]:
from sklearn.feature_extraction.text import CountVectorizer

In [10]:
number=0
pur=data.reindex(columns=['title','article'])
test_title=pur['title'].iloc[number]
test_article=pur['article'].iloc[number]
test_article_list=kkma.sentences(test_article)
total=test_title+"\n"+test_article
total_list=[test_title]+test_article_list

In [11]:
print("test_title: " + test_title + "\n")
print("test_article: " + test_article + "\n")
print("test_article_list: ",test_article_list , "\n")
print("total: ",total , "\n")
print("total_list: ",total_list)

test_title: [통계뉴스]문재인 앞서고 안철수-홍준표 혼전 양상

test_article: 지난주 대선후보 여론조사에서는 더불어민주당 문재인 후보와 국민의당 안철수 후보의 평균 지지율 격차가 더 벌어진 가운데 자유한국당 홍준표 후보의 지지율이 처음으로 두자리 수를 기록했습니다. ,[동아일보],22~28일 중앙선거관리위원회 중앙선거여론조사심의위원회에 등록된 여론조사 중 전국 단위, 5자구도 질문을 포함한 11건의 여론조사를 종합 분석해 평균치를 낸 결과입니다.,※한국리서치(내일신문), 리서치앤리서치, 한국사회여론연구소, 칸타코리아, 조원씨앤아이, 메트릭스코퍼레이션, 알앤써치, 한국리서치(한국일보·코리아타임즈), 리얼미터, 한국리서치(JTBC·25일 조사), 한국리서치(JTBC·26일 조사) 자료 종합,문 후보의 평균 지지율은 40.4%로 전주(42.5%) 대비 2.1%포인트 하락한 1위였는데요. ,2위 안 후보의 지지율은 30% 선이 무너졌습니다. 전주(32.8%) 대비 4.5%포인트 하락한 28.3%였죠. ,1,2위간 지지율 격차는 12.1%포인트 차. 전주(9.7%) 대비 2.4%포인트 더 벌어졌습니다. ,반면 3위 홍 후보는 ‘돼지발정제’ 논란에도 전주(9.5%) 대비 1.5%포인트 상승한 11.0%였습니다. ,4위 정의당 심상정 후보는 1.6%포인트 상승한 5.1%, 5위 바른정당 유승민 후보는 0.8%포인트 상승한 4.2%였습니다.,연령별 지지율은 차이가 있었는데요. ,심 후보는 19~29세(10.7%) 유권자 층에서 강세를 보였습니다. ,특히 한국리서치(한국일보·코리아타임즈) 여론조사에서는 심 후보의 19~29세 지지율이 17.8%로 안 후보(16.7%)를 제치고 2위를 차지하기도 했죠.,※각 여론조사와 관련한 자세한 내용은 중앙선거관리위원회 중앙선거여론조사심의위원회 홈페이지(www.nesdc.go.kr) 참조.

test_article_list:  ['지난주 대선후보 여론조사에서는 더불어 민주당 문 재인 후보와 국민의 당 안 철수 후보의 평균

In [12]:
print(type(test_title))
print(type(test_article))
print(type(test_article_list))
print(type(total))
print(type(total_list))

<class 'str'>
<class 'str'>
<class 'list'>
<class 'str'>
<class 'list'>


# textrank 패키지 사용

In [49]:
from __future__ import print_function
from textrankr import TextRank

textrank = TextRank(test_article)
print(textrank.summarize())

,1,2위간 지지율 격차는 12.1%포인트 차.
,반면 3위 홍 후보는 ‘돼지발정제’ 논란에도 전주(9.5%) 대비 1.5%포인트 상승한 11.0%였습니다.
,특히 한국리서치(한국일보·코리아타임즈) 여론조사에서는 심 후보의 19~29세 지지율이 17.8%로 안 후보(16.7%)를 제치고 2위를 차지하기도 했죠.,※각 여론조사와 관련한 자세한 내용은 중앙선거관리위원회 중앙선거여론조사심의위원회 홈페이지(www.nesdc.go.kr) 참조.


In [50]:
test_article

'지난주 대선후보 여론조사에서는 더불어민주당 문재인 후보와 국민의당 안철수 후보의 평균 지지율 격차가 더 벌어진 가운데 자유한국당 홍준표 후보의 지지율이 처음으로 두자리 수를 기록했습니다. ,[동아일보],22~28일 중앙선거관리위원회 중앙선거여론조사심의위원회에 등록된 여론조사 중 전국 단위, 5자구도 질문을 포함한 11건의 여론조사를 종합 분석해 평균치를 낸 결과입니다.,※한국리서치(내일신문), 리서치앤리서치, 한국사회여론연구소, 칸타코리아, 조원씨앤아이, 메트릭스코퍼레이션, 알앤써치, 한국리서치(한국일보·코리아타임즈), 리얼미터, 한국리서치(JTBC·25일 조사), 한국리서치(JTBC·26일 조사) 자료 종합,문 후보의 평균 지지율은 40.4%로 전주(42.5%) 대비 2.1%포인트 하락한 1위였는데요. ,2위 안 후보의 지지율은 30% 선이 무너졌습니다. 전주(32.8%) 대비 4.5%포인트 하락한 28.3%였죠. ,1,2위간 지지율 격차는 12.1%포인트 차. 전주(9.7%) 대비 2.4%포인트 더 벌어졌습니다. ,반면 3위 홍 후보는 ‘돼지발정제’ 논란에도 전주(9.5%) 대비 1.5%포인트 상승한 11.0%였습니다. ,4위 정의당 심상정 후보는 1.6%포인트 상승한 5.1%, 5위 바른정당 유승민 후보는 0.8%포인트 상승한 4.2%였습니다.,연령별 지지율은 차이가 있었는데요. ,심 후보는 19~29세(10.7%) 유권자 층에서 강세를 보였습니다. ,특히 한국리서치(한국일보·코리아타임즈) 여론조사에서는 심 후보의 19~29세 지지율이 17.8%로 안 후보(16.7%)를 제치고 2위를 차지하기도 했죠.,※각 여론조사와 관련한 자세한 내용은 중앙선거관리위원회 중앙선거여론조사심의위원회 홈페이지(www.nesdc.go.kr) 참조.'

# lextrank 패키지 사용

In [51]:
from __future__ import print_function
from lexrankr import LexRank

lexrank = LexRank()  # can init with various settings
lexrank.summarize(test_article)
summaries = lexrank.probe(None)  # `num_summaries` can be `None` (using auto-detected topics)
for summary in summaries:
    print(summary)

,반면 3위 홍 후보는 ‘돼지발정제’ 논란에도 전주(9.5%) 대비 1.5%포인트 상승한 11.0%였습니다
,4위 정의당 심상정 후보는 1.6%포인트 상승한 5.1%, 5위 바른정당 유승민 후보는 0.8%포인트 상승한 4.2%였습니다.,연령별 지지율은 차이가 있었는데요


In [52]:
test_article

'지난주 대선후보 여론조사에서는 더불어민주당 문재인 후보와 국민의당 안철수 후보의 평균 지지율 격차가 더 벌어진 가운데 자유한국당 홍준표 후보의 지지율이 처음으로 두자리 수를 기록했습니다. ,[동아일보],22~28일 중앙선거관리위원회 중앙선거여론조사심의위원회에 등록된 여론조사 중 전국 단위, 5자구도 질문을 포함한 11건의 여론조사를 종합 분석해 평균치를 낸 결과입니다.,※한국리서치(내일신문), 리서치앤리서치, 한국사회여론연구소, 칸타코리아, 조원씨앤아이, 메트릭스코퍼레이션, 알앤써치, 한국리서치(한국일보·코리아타임즈), 리얼미터, 한국리서치(JTBC·25일 조사), 한국리서치(JTBC·26일 조사) 자료 종합,문 후보의 평균 지지율은 40.4%로 전주(42.5%) 대비 2.1%포인트 하락한 1위였는데요. ,2위 안 후보의 지지율은 30% 선이 무너졌습니다. 전주(32.8%) 대비 4.5%포인트 하락한 28.3%였죠. ,1,2위간 지지율 격차는 12.1%포인트 차. 전주(9.7%) 대비 2.4%포인트 더 벌어졌습니다. ,반면 3위 홍 후보는 ‘돼지발정제’ 논란에도 전주(9.5%) 대비 1.5%포인트 상승한 11.0%였습니다. ,4위 정의당 심상정 후보는 1.6%포인트 상승한 5.1%, 5위 바른정당 유승민 후보는 0.8%포인트 상승한 4.2%였습니다.,연령별 지지율은 차이가 있었는데요. ,심 후보는 19~29세(10.7%) 유권자 층에서 강세를 보였습니다. ,특히 한국리서치(한국일보·코리아타임즈) 여론조사에서는 심 후보의 19~29세 지지율이 17.8%로 안 후보(16.7%)를 제치고 2위를 차지하기도 했죠.,※각 여론조사와 관련한 자세한 내용은 중앙선거관리위원회 중앙선거여론조사심의위원회 홈페이지(www.nesdc.go.kr) 참조.'

# space bar 기준으로 나눈 것 분류하기

In [53]:
vectorizer = CountVectorizer(min_df=2)
#단어주머니를 만들기 전에 속성값을 지정해줘야 한다.
print(vectorizer)
X_train = vectorizer.fit_transform(test_article_list)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=2,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)


In [54]:
print("\n<post_vec>\n",X_train)
print("\n<post_vec array form>\n",X_train.toarray())
num_samples, num_features = X_train.shape
#vectorizer가 예상 단어를 알 수 있도록 vectorizer에게 전체 데이터셋을 알려야 한다.

print("\n#sample: %d, #features: %d" % (num_samples,num_features))
#e5개의 게시물에는 25개의 각기 다른 단어가 있다.
print("\nfeature_names =",vectorizer.get_feature_names())
#25개의 각기 다른 단어들을 출력해보았다.


<post_vec>
   (0, 18)	1
  (0, 24)	1
  (0, 16)	1
  (0, 21)	1
  (0, 26)	2
  (0, 8)	1
  (1, 13)	1
  (1, 6)	1
  (1, 7)	2
  (1, 14)	1
  (1, 10)	1
  (1, 15)	1
  (1, 1)	1
  (1, 11)	1
  (2, 23)	1
  (2, 22)	1
  (2, 3)	1
  (2, 12)	1
  (2, 17)	2
  (2, 20)	1
  (2, 19)	2
  (2, 4)	6
  (2, 13)	1
  (2, 11)	1
  (2, 24)	5
  :	:
  (5, 3)	1
  (5, 12)	1
  (6, 9)	1
  (6, 5)	2
  (6, 25)	2
  (6, 22)	2
  (7, 2)	1
  (7, 0)	1
  (7, 25)	1
  (7, 17)	1
  (8, 2)	1
  (8, 0)	1
  (8, 20)	1
  (8, 19)	1
  (8, 4)	1
  (8, 11)	1
  (8, 18)	1
  (8, 24)	2
  (8, 26)	1
  (8, 8)	1
  (9, 6)	1
  (9, 7)	1
  (9, 14)	1
  (9, 10)	2
  (9, 15)	1

<post_vec array form>
 [[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 1 0 0 1 0 0 1 0 2]
 [0 1 0 0 0 0 1 2 0 0 1 1 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 6 0 0 0 0 0 0 1 1 1 0 0 0 2 0 2 1 1 1 1 5 0 2]
 [0 1 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 1 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 2 0 0 0 0]
 [0 0 0 1 0 1 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 1 0]
 [0 0 0 0 0 2 0 0 0 1 0 0 0 0 0 

In [55]:
sum(X_train.toarray().T)

array([ 7,  9, 25,  5,  5,  6,  7,  4, 11,  6], dtype=int64)

In [56]:
check=list(sum(X_train.toarray().T)/num_features > 0.3)
check

[False, True, True, False, False, False, False, False, True, False]

In [57]:
len_test=len(sum(X_train.toarray().T))

In [58]:
test_index=[i for i in range(len_test) if check[i]==True]
test_index

[1, 2, 8]

In [59]:
for i in test_index:
    print(test_article_list[i])

[ 동아 일보] ,22 ~28 일 중앙선거관리 위원회 중앙선거 여론조사 심의 위원회에 등록된 여론조사 중 전국 단위, 5 자구도 질문을 포함한 11건의 여론조사를 종합 분석해 평균치를 낸 결과입니다.,
※ 한국 리서치( 내일신문), 리서치 앤 리서치, 한국사회 여론 연구소, 칸 타 코리아, 조원 씨 앤 아이, 메트릭스 코퍼 레이션, 알 앤 써 치, 한국 리서치( 한국 일보· 코리아 타임즈), 리얼 미터, 한국 리서치 (JTBC ·25 일 조사), 한국 리서치 (JTBC ·26 일 조사) 자료 종합, 문 후보의 평균 지지율은 40.4% 로 전주 (42.5%) 대비 2.1% 포인트 하락한 1위였는데요. ,2 위 안 후보의 지지율은 30% 선이 무너졌습니다.
특히 한국 리서치( 한국 일보· 코리아 타임즈) 여론조사에서는 심 후보의 19~29 세 지지율이 17.8% 로 안 후보 (16.7% )를 제치고 2위를 차지하기도 했죠.,


In [60]:
test_article

'지난주 대선후보 여론조사에서는 더불어민주당 문재인 후보와 국민의당 안철수 후보의 평균 지지율 격차가 더 벌어진 가운데 자유한국당 홍준표 후보의 지지율이 처음으로 두자리 수를 기록했습니다. ,[동아일보],22~28일 중앙선거관리위원회 중앙선거여론조사심의위원회에 등록된 여론조사 중 전국 단위, 5자구도 질문을 포함한 11건의 여론조사를 종합 분석해 평균치를 낸 결과입니다.,※한국리서치(내일신문), 리서치앤리서치, 한국사회여론연구소, 칸타코리아, 조원씨앤아이, 메트릭스코퍼레이션, 알앤써치, 한국리서치(한국일보·코리아타임즈), 리얼미터, 한국리서치(JTBC·25일 조사), 한국리서치(JTBC·26일 조사) 자료 종합,문 후보의 평균 지지율은 40.4%로 전주(42.5%) 대비 2.1%포인트 하락한 1위였는데요. ,2위 안 후보의 지지율은 30% 선이 무너졌습니다. 전주(32.8%) 대비 4.5%포인트 하락한 28.3%였죠. ,1,2위간 지지율 격차는 12.1%포인트 차. 전주(9.7%) 대비 2.4%포인트 더 벌어졌습니다. ,반면 3위 홍 후보는 ‘돼지발정제’ 논란에도 전주(9.5%) 대비 1.5%포인트 상승한 11.0%였습니다. ,4위 정의당 심상정 후보는 1.6%포인트 상승한 5.1%, 5위 바른정당 유승민 후보는 0.8%포인트 상승한 4.2%였습니다.,연령별 지지율은 차이가 있었는데요. ,심 후보는 19~29세(10.7%) 유권자 층에서 강세를 보였습니다. ,특히 한국리서치(한국일보·코리아타임즈) 여론조사에서는 심 후보의 19~29세 지지율이 17.8%로 안 후보(16.7%)를 제치고 2위를 차지하기도 했죠.,※각 여론조사와 관련한 자세한 내용은 중앙선거관리위원회 중앙선거여론조사심의위원회 홈페이지(www.nesdc.go.kr) 참조.'

In [61]:
test_title

'[통계뉴스]문재인 앞서고 안철수-홍준표 혼전 양상'

# 추가작업 : 명사로 자르기 + 많이 나온 단어에 가중치 주기 + title내용 포함

In [62]:
from konlpy.tag import Hannanum
from konlpy.tag import Komoran
from konlpy.tag import Twitter
from konlpy.tag import Kkma
from konlpy.utils import pprint
twitter = Twitter()
doc=twitter.nouns(total)
doc

['통계',
 '뉴스',
 '문재인',
 '안철수',
 '홍준표',
 '혼전',
 '양상',
 '지난주',
 '대선',
 '후보',
 '여론조사',
 '민주당',
 '문재인',
 '후보',
 '국민의당',
 '안철수',
 '후보',
 '평균',
 '지지율',
 '격차',
 '더',
 '가운데',
 '자유',
 '한국',
 '홍준표',
 '후보',
 '지지율',
 '처음',
 '자리',
 '수',
 '기록',
 '동아일보',
 '일',
 '중앙',
 '선거',
 '관리',
 '위원회',
 '중앙',
 '선거',
 '여론조사',
 '심의',
 '위원회',
 '등록',
 '여론조사',
 '중',
 '전국',
 '단위',
 '자구',
 '질문',
 '건의',
 '여론조사',
 '종합',
 '평균',
 '결과',
 '한국',
 '리서치',
 '내일',
 '신문',
 '리서치',
 '앤',
 '리서치',
 '한국',
 '사회',
 '여론',
 '연구소',
 '칸타',
 '코리아',
 '조원',
 '앤',
 '아이',
 '메',
 '트릭',
 '스',
 '코퍼레이션',
 '알',
 '앤써',
 '치',
 '한국',
 '리서치',
 '한국',
 '일보',
 '코리아타임즈',
 '리얼미터',
 '한국',
 '리서치',
 '일',
 '조사',
 '한국',
 '리서치',
 '일',
 '조사',
 '자료',
 '종합',
 '문',
 '후보',
 '평균',
 '지지율',
 '로',
 '전주',
 '대비',
 '포인트',
 '하락',
 '위',
 '위',
 '안',
 '후보',
 '지지율',
 '선',
 '전주',
 '대비',
 '포인트',
 '하락',
 '위',
 '지지율',
 '격차',
 '포인트',
 '차',
 '전주',
 '대비',
 '포인트',
 '더',
 '반면',
 '위',
 '홍',
 '후보',
 '돼지',
 '발정',
 '제',
 '논란',
 '전주',
 '대비',
 '포인트',
 '상승',
 '위',
 '정의당',
 '심상정',
 '후보',
 '포인트',
 '상승',

In [63]:
docs=pd.Series(doc)
print(docs.value_counts())
select_docs=docs.value_counts()[docs.value_counts()>1]

max_words=list(pd.DataFrame(select_docs).index)
count_words=select_docs.values
print(max_words)
print(count_words)

후보        12
한국         9
리서치        7
포인트        7
지지율        7
위          7
여론조사       7
위원회        4
선거         4
중앙         4
대비         4
전주         4
상승         3
평균         3
일          3
문재인        2
조사         2
종합         2
로          2
앤          2
일보         2
홍준표        2
관리         2
더          2
안철수        2
하락         2
심          2
코리아타임즈     2
격차         2
제          2
          ..
층          1
알          1
홍          1
결과         1
신문         1
리얼미터       1
중          1
코리아        1
자리         1
칸타         1
자유         1
메          1
정당         1
국민의당       1
처음         1
트릭         1
사회         1
단위         1
별          1
유승민        1
반면         1
앤써         1
지난주        1
내일         1
강세         1
대선         1
심상정        1
문          1
발정         1
뉴스         1
Length: 98, dtype: int64
['후보', '한국', '리서치', '포인트', '지지율', '위', '여론조사', '위원회', '선거', '중앙', '대비', '전주', '상승', '평균', '일', '문재인', '조사', '종합', '로', '앤', '일보', '홍준표', '관리', '더', '안철수', '하락', '심', '코리아타임즈', '격차', 

In [64]:
vect = CountVectorizer().fit(max_words)
doc_train = vect.transform(test_article_list)

print("\n<post_vec>\n",doc_train)
print("\n<post_vec array form>\n",doc_train.toarray())
doc_num_samples, doc_num_features = doc_train.shape
#vectorizer가 예상 단어를 알 수 있도록 vectorizer에게 전체 데이터셋을 알려야 한다.

print("\n#sample: %d, #features: %d" % (doc_num_samples,doc_num_features))
#e5개의 게시물에는 25개의 각기 다른 단어가 있다.
print("\nfeature_names =",vect.get_feature_names())
#25개의 각기 다른 단어들을 출력해보았다.


<post_vec>
   (0, 16)	1
  (0, 18)	1
  (0, 21)	1
  (1, 7)	1
  (1, 9)	2
  (1, 10)	1
  (1, 11)	1
  (1, 14)	1
  (2, 2)	1
  (2, 3)	6
  (2, 11)	1
  (2, 12)	1
  (2, 13)	2
  (2, 14)	1
  (2, 18)	1
  (2, 19)	1
  (2, 21)	5
  (3, 2)	1
  (3, 12)	1
  (3, 19)	1
  (4, 2)	1
  (4, 12)	1
  (4, 16)	1
  (4, 19)	2
  (5, 2)	1
  (5, 12)	1
  (5, 19)	1
  (6, 19)	2
  (8, 3)	1
  (8, 11)	1
  (8, 21)	2
  (8, 23)	1
  (9, 7)	1
  (9, 9)	1
  (9, 10)	2

<post_vec array form>
 [[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 1 0 0]
 [0 0 0 0 0 0 0 1 0 2 1 1 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 1 6 0 0 0 0 0 0 0 1 1 2 1 0 0 0 1 1 0 5 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 2 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 2 0 1]
 [0 0 0 0 0 0 0 1 0 1 2 0 0 0 0 0 0 0 0 0 0 0 0 0]]

#sample: 10, #features: 24

feature_names

In [65]:
vect.get_feature_names()

['격차',
 '관리',
 '대비',
 '리서치',
 '문재인',
 '상승',
 '선거',
 '심의',
 '안철수',
 '여론조사',
 '위원회',
 '일보',
 '전주',
 '조사',
 '종합',
 '중앙',
 '지지율',
 '코리아타임즈',
 '평균',
 '포인트',
 '하락',
 '한국',
 '홍준표',
 '후보']

In [66]:
words_which_index=[max_words.index(i) for i in vect.get_feature_names()]
words_which_index

[28,
 22,
 10,
 2,
 15,
 12,
 8,
 31,
 24,
 6,
 7,
 20,
 11,
 16,
 17,
 9,
 4,
 27,
 13,
 3,
 25,
 1,
 21,
 0]

In [71]:
words_converter = lambda x: max_words[x]
count_converter = lambda x: count_words[x]
words_matrix=pd.Series(words_which_index).apply(words_converter)
count_matrix=pd.Series(words_which_index).apply(count_converter)
new_matrix=pd.DataFrame({'word': words_matrix,'count': count_matrix})
new_matrix
#weight

count    word
0       2      격차
1       2      관리
2       4      대비
3       7     리서치
4       2     문재인
5       3      상승
6       4      선거
7       2      심의
8       2     안철수
9       7    여론조사
10      4     위원회
11      2      일보
12      4      전주
13      2      조사
14      2      종합
15      4      중앙
16      7     지지율
17      2  코리아타임즈
18      3      평균
19      7     포인트
20      2      하락
21      9      한국
22      2     홍준표
23     12      후보

In [68]:
doc_train.toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
        0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 2, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0],
       [0, 0, 1, 6, 0, 0, 0, 0, 0, 0, 0, 1, 1, 2, 1, 0, 0, 0, 1, 1, 0, 5,
        0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 2, 0, 0,
        0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0,
        0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2,
        0, 1],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0]])

In [73]:
doc_check=np.array(pd.DataFrame(np.dot(doc_train.toarray(),new_matrix)).ix[:,0])
doc_check
#weight준 값

/Users/jinseokryu/anaconda/envs/tensorflow/lib/python3.5/site-packages/ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate_ix
  """Entry point for launching an IPython kernel.


array([19, 24, 113, 15, 29, 15, 14, 0, 39, 17], dtype=object)

In [74]:
doc_index = np.array(doc_check/sum(doc_check) > 1/len(doc_check))
doc_index
#평균이상인 것들만 추출

array([False, False,  True, False,  True, False, False, False,  True, False], dtype=bool)

In [75]:
doc_test_index=[i for i in range(len(doc_index)) if doc_index[i]==True]
doc_test_index

[2, 4, 8]

In [76]:
for i in doc_test_index:
    print(test_article_list[i])

※ 한국 리서치( 내일신문), 리서치 앤 리서치, 한국사회 여론 연구소, 칸 타 코리아, 조원 씨 앤 아이, 메트릭스 코퍼 레이션, 알 앤 써 치, 한국 리서치( 한국 일보· 코리아 타임즈), 리얼 미터, 한국 리서치 (JTBC ·25 일 조사), 한국 리서치 (JTBC ·26 일 조사) 자료 종합, 문 후보의 평균 지지율은 40.4% 로 전주 (42.5%) 대비 2.1% 포인트 하락한 1위였는데요. ,2 위 안 후보의 지지율은 30% 선이 무너졌습니다.
위 간 지지율 격차는 12.1% 포인트 차. 전주 (9.7%) 대비 2.4% 포인트 더 벌어졌습니다. ,
특히 한국 리서치( 한국 일보· 코리아 타임즈) 여론조사에서는 심 후보의 19~29 세 지지율이 17.8% 로 안 후보 (16.7% )를 제치고 2위를 차지하기도 했죠.,


In [77]:
print(test_article)

지난주 대선후보 여론조사에서는 더불어민주당 문재인 후보와 국민의당 안철수 후보의 평균 지지율 격차가 더 벌어진 가운데 자유한국당 홍준표 후보의 지지율이 처음으로 두자리 수를 기록했습니다. ,[동아일보],22~28일 중앙선거관리위원회 중앙선거여론조사심의위원회에 등록된 여론조사 중 전국 단위, 5자구도 질문을 포함한 11건의 여론조사를 종합 분석해 평균치를 낸 결과입니다.,※한국리서치(내일신문), 리서치앤리서치, 한국사회여론연구소, 칸타코리아, 조원씨앤아이, 메트릭스코퍼레이션, 알앤써치, 한국리서치(한국일보·코리아타임즈), 리얼미터, 한국리서치(JTBC·25일 조사), 한국리서치(JTBC·26일 조사) 자료 종합,문 후보의 평균 지지율은 40.4%로 전주(42.5%) 대비 2.1%포인트 하락한 1위였는데요. ,2위 안 후보의 지지율은 30% 선이 무너졌습니다. 전주(32.8%) 대비 4.5%포인트 하락한 28.3%였죠. ,1,2위간 지지율 격차는 12.1%포인트 차. 전주(9.7%) 대비 2.4%포인트 더 벌어졌습니다. ,반면 3위 홍 후보는 ‘돼지발정제’ 논란에도 전주(9.5%) 대비 1.5%포인트 상승한 11.0%였습니다. ,4위 정의당 심상정 후보는 1.6%포인트 상승한 5.1%, 5위 바른정당 유승민 후보는 0.8%포인트 상승한 4.2%였습니다.,연령별 지지율은 차이가 있었는데요. ,심 후보는 19~29세(10.7%) 유권자 층에서 강세를 보였습니다. ,특히 한국리서치(한국일보·코리아타임즈) 여론조사에서는 심 후보의 19~29세 지지율이 17.8%로 안 후보(16.7%)를 제치고 2위를 차지하기도 했죠.,※각 여론조사와 관련한 자세한 내용은 중앙선거관리위원회 중앙선거여론조사심의위원회 홈페이지(www.nesdc.go.kr) 참조.


In [78]:
test_title

'[통계뉴스]문재인 앞서고 안철수-홍준표 혼전 양상'

# 추가작업 : 제목에 가중치 주기

In [88]:
from konlpy.tag import Hannanum
from konlpy.tag import Komoran
from konlpy.tag import Twitter
from konlpy.tag import Kkma
from konlpy.utils import pprint
twitter = Twitter()
doc=twitter.nouns(test_article)
max=np.array(pd.Series(doc).value_counts())[0]
#제목에 들어간 단어들은 article에 들어간 가장 많이 나온 단어의 횟수만큼 더해줌
print(pd.Series(doc).value_counts())
print(max,"\n")
doc_t=list(twitter.nouns(test_title))*max
print(doc_t,"\n")
total_doc=doc+doc_t
print(total_doc,"\n")

후보        12
한국         9
포인트        7
리서치        7
지지율        7
여론조사       7
위          7
전주         4
선거         4
중앙         4
대비         4
위원회        4
일          3
상승         3
평균         3
일보         2
로          2
앤          2
격차         2
종합         2
관리         2
조사         2
더          2
제          2
세          2
심의         2
안          2
심          2
코리아타임즈     2
하락         2
          ..
질문         1
선          1
기록         1
층          1
홍          1
결과         1
정당         1
리얼미터       1
코리아        1
자리         1
칸타         1
자유         1
메          1
앤써         1
국민의당       1
처음         1
신문         1
트릭         1
단위         1
별          1
내용         1
반면         1
지난주        1
내일         1
대선         1
심상정        1
문          1
유승민        1
발정         1
수          1
Length: 94, dtype: int64
12 

['통계', '뉴스', '문재인', '안철수', '홍준표', '혼전', '양상', '통계', '뉴스', '문재인', '안철수', '홍준표', '혼전', '양상', '통계', '뉴스', '문재인', '안철수', '홍준표', '혼전', '양상', '통계', '뉴스', '문재인', '안철수', '홍준표', '혼전', '양

In [89]:
totals=pd.Series(total_doc)

select_totals=totals.value_counts()[totals.value_counts()>1]

totals_max_words=list(pd.DataFrame(select_totals).index)
totals_count_words=select_totals.values
print(totals_max_words)
print(totals_count_words)

['문재인', '홍준표', '안철수', '뉴스', '통계', '후보', '양상', '혼전', '한국', '포인트', '여론조사', '위', '지지율', '리서치', '전주', '선거', '중앙', '위원회', '대비', '평균', '일', '상승', '코리아타임즈', '격차', '앤', '로', '심', '안', '일보', '하락', '세', '심의', '관리', '더', '종합', '조사', '제']
[13 13 13 12 12 12 12 12  9  7  7  7  7  7  4  4  4  4  4  3  3  3  2  2  2
  2  2  2  2  2  2  2  2  2  2  2  2]


In [90]:
vector = CountVectorizer().fit(totals_max_words)
total_train = vector.transform(test_article_list)

print("\n<post_vec>\n",total_train)
print("\n<post_vec array form>\n",total_train.toarray())
total_num_samples, total_num_features = total_train.shape
#vectorizer가 예상 단어를 알 수 있도록 vectorizer에게 전체 데이터셋을 알려야 한다.

print("\n#sample: %d, #features: %d" % (total_num_samples,total_num_features))
#e5개의 게시물에는 25개의 각기 다른 단어가 있다.
print("\nfeature_names =",vector.get_feature_names())
#25개의 각기 다른 단어들을 출력해보았다.


<post_vec>
   (0, 18)	1
  (0, 21)	1
  (0, 24)	1
  (1, 8)	1
  (1, 11)	2
  (1, 12)	1
  (1, 13)	1
  (1, 16)	1
  (2, 3)	1
  (2, 4)	6
  (2, 13)	1
  (2, 14)	1
  (2, 15)	2
  (2, 16)	1
  (2, 21)	1
  (2, 22)	1
  (2, 24)	5
  (3, 3)	1
  (3, 14)	1
  (3, 22)	1
  (4, 3)	1
  (4, 14)	1
  (4, 18)	1
  (4, 22)	2
  (5, 3)	1
  (5, 14)	1
  (5, 22)	1
  (6, 22)	2
  (8, 4)	1
  (8, 13)	1
  (8, 24)	2
  (8, 27)	1
  (9, 8)	1
  (9, 11)	1
  (9, 12)	2

<post_vec array form>
 [[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 2 1 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 6 0 0 0 0 0 0 0 0 1 1 2 1 0 0 0 0 1 1 0 5 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 2 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 2 0 0 1]
 [0 0 0 0 0 0 0 0 1 

In [91]:
total_words_which_index=[totals_max_words.index(i) for i in vector.get_feature_names()]
total_words_which_index

[23,
 32,
 3,
 18,
 13,
 0,
 21,
 15,
 31,
 2,
 6,
 10,
 17,
 28,
 14,
 35,
 34,
 16,
 12,
 22,
 4,
 19,
 9,
 29,
 8,
 7,
 1,
 5]

In [92]:
words_converter = lambda x: totals_max_words[x]
count_converter = lambda x: totals_count_words[x]
total_words_matrix=pd.Series(total_words_which_index).apply(words_converter)
total_count_matrix=pd.Series(total_words_which_index).apply(count_converter)
total_new_matrix=pd.DataFrame({'word': total_words_matrix,'count': total_count_matrix})
total_new_matrix

count    word
0       2      격차
1       2      관리
2      12      뉴스
3       4      대비
4       7     리서치
5      13     문재인
6       3      상승
7       4      선거
8       2      심의
9      13     안철수
10     12      양상
11      7    여론조사
12      4     위원회
13      2      일보
14      4      전주
15      2      조사
16      2      종합
17      4      중앙
18      7     지지율
19      2  코리아타임즈
20     12      통계
21      3      평균
22      7     포인트
23      2      하락
24      9      한국
25     12      혼전
26     13     홍준표
27     12      후보

In [93]:
total_train.toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
        0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 2, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 6, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 2, 1, 0, 0, 0, 0, 1,
        1, 0, 5, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
        2, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        2, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 2, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 

In [94]:
total_check=np.array(pd.DataFrame(np.dot(total_train.toarray(),total_new_matrix)).ix[:,0])
total_check

/Users/jinseokryu/anaconda/envs/tensorflow/lib/python3.5/site-packages/ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate_ix
  """Entry point for launching an IPython kernel.


array([19, 24, 113, 15, 29, 15, 14, 0, 39, 17], dtype=object)

In [95]:
total_index = np.array(total_check/sum(total_check) > 1/len(total_check))
total_index

array([False, False,  True, False,  True, False, False, False,  True, False], dtype=bool)

In [96]:
total_test_index=[i for i in range(len(total_index)) if total_index[i]==True]
total_test_index

[2, 4, 8]

In [97]:
for i in total_test_index:
    print(test_article_list[i])

※ 한국 리서치( 내일신문), 리서치 앤 리서치, 한국사회 여론 연구소, 칸 타 코리아, 조원 씨 앤 아이, 메트릭스 코퍼 레이션, 알 앤 써 치, 한국 리서치( 한국 일보· 코리아 타임즈), 리얼 미터, 한국 리서치 (JTBC ·25 일 조사), 한국 리서치 (JTBC ·26 일 조사) 자료 종합, 문 후보의 평균 지지율은 40.4% 로 전주 (42.5%) 대비 2.1% 포인트 하락한 1위였는데요. ,2 위 안 후보의 지지율은 30% 선이 무너졌습니다.
위 간 지지율 격차는 12.1% 포인트 차. 전주 (9.7%) 대비 2.4% 포인트 더 벌어졌습니다. ,
특히 한국 리서치( 한국 일보· 코리아 타임즈) 여론조사에서는 심 후보의 19~29 세 지지율이 17.8% 로 안 후보 (16.7% )를 제치고 2위를 차지하기도 했죠.,


In [98]:
test_article

'지난주 대선후보 여론조사에서는 더불어민주당 문재인 후보와 국민의당 안철수 후보의 평균 지지율 격차가 더 벌어진 가운데 자유한국당 홍준표 후보의 지지율이 처음으로 두자리 수를 기록했습니다. ,[동아일보],22~28일 중앙선거관리위원회 중앙선거여론조사심의위원회에 등록된 여론조사 중 전국 단위, 5자구도 질문을 포함한 11건의 여론조사를 종합 분석해 평균치를 낸 결과입니다.,※한국리서치(내일신문), 리서치앤리서치, 한국사회여론연구소, 칸타코리아, 조원씨앤아이, 메트릭스코퍼레이션, 알앤써치, 한국리서치(한국일보·코리아타임즈), 리얼미터, 한국리서치(JTBC·25일 조사), 한국리서치(JTBC·26일 조사) 자료 종합,문 후보의 평균 지지율은 40.4%로 전주(42.5%) 대비 2.1%포인트 하락한 1위였는데요. ,2위 안 후보의 지지율은 30% 선이 무너졌습니다. 전주(32.8%) 대비 4.5%포인트 하락한 28.3%였죠. ,1,2위간 지지율 격차는 12.1%포인트 차. 전주(9.7%) 대비 2.4%포인트 더 벌어졌습니다. ,반면 3위 홍 후보는 ‘돼지발정제’ 논란에도 전주(9.5%) 대비 1.5%포인트 상승한 11.0%였습니다. ,4위 정의당 심상정 후보는 1.6%포인트 상승한 5.1%, 5위 바른정당 유승민 후보는 0.8%포인트 상승한 4.2%였습니다.,연령별 지지율은 차이가 있었는데요. ,심 후보는 19~29세(10.7%) 유권자 층에서 강세를 보였습니다. ,특히 한국리서치(한국일보·코리아타임즈) 여론조사에서는 심 후보의 19~29세 지지율이 17.8%로 안 후보(16.7%)를 제치고 2위를 차지하기도 했죠.,※각 여론조사와 관련한 자세한 내용은 중앙선거관리위원회 중앙선거여론조사심의위원회 홈페이지(www.nesdc.go.kr) 참조.'

In [99]:
test_title

'[통계뉴스]문재인 앞서고 안철수-홍준표 혼전 양상'

# Summary

### 뉴스 기사 제목

In [100]:
test_title

'[통계뉴스]문재인 앞서고 안철수-홍준표 혼전 양상'

### 뉴스 기사 내용

In [101]:
test_article

'지난주 대선후보 여론조사에서는 더불어민주당 문재인 후보와 국민의당 안철수 후보의 평균 지지율 격차가 더 벌어진 가운데 자유한국당 홍준표 후보의 지지율이 처음으로 두자리 수를 기록했습니다. ,[동아일보],22~28일 중앙선거관리위원회 중앙선거여론조사심의위원회에 등록된 여론조사 중 전국 단위, 5자구도 질문을 포함한 11건의 여론조사를 종합 분석해 평균치를 낸 결과입니다.,※한국리서치(내일신문), 리서치앤리서치, 한국사회여론연구소, 칸타코리아, 조원씨앤아이, 메트릭스코퍼레이션, 알앤써치, 한국리서치(한국일보·코리아타임즈), 리얼미터, 한국리서치(JTBC·25일 조사), 한국리서치(JTBC·26일 조사) 자료 종합,문 후보의 평균 지지율은 40.4%로 전주(42.5%) 대비 2.1%포인트 하락한 1위였는데요. ,2위 안 후보의 지지율은 30% 선이 무너졌습니다. 전주(32.8%) 대비 4.5%포인트 하락한 28.3%였죠. ,1,2위간 지지율 격차는 12.1%포인트 차. 전주(9.7%) 대비 2.4%포인트 더 벌어졌습니다. ,반면 3위 홍 후보는 ‘돼지발정제’ 논란에도 전주(9.5%) 대비 1.5%포인트 상승한 11.0%였습니다. ,4위 정의당 심상정 후보는 1.6%포인트 상승한 5.1%, 5위 바른정당 유승민 후보는 0.8%포인트 상승한 4.2%였습니다.,연령별 지지율은 차이가 있었는데요. ,심 후보는 19~29세(10.7%) 유권자 층에서 강세를 보였습니다. ,특히 한국리서치(한국일보·코리아타임즈) 여론조사에서는 심 후보의 19~29세 지지율이 17.8%로 안 후보(16.7%)를 제치고 2위를 차지하기도 했죠.,※각 여론조사와 관련한 자세한 내용은 중앙선거관리위원회 중앙선거여론조사심의위원회 홈페이지(www.nesdc.go.kr) 참조.'

### textrank 이용한 요약

In [102]:
print(textrank.summarize())

,1,2위간 지지율 격차는 12.1%포인트 차.
,반면 3위 홍 후보는 ‘돼지발정제’ 논란에도 전주(9.5%) 대비 1.5%포인트 상승한 11.0%였습니다.
,특히 한국리서치(한국일보·코리아타임즈) 여론조사에서는 심 후보의 19~29세 지지율이 17.8%로 안 후보(16.7%)를 제치고 2위를 차지하기도 했죠.,※각 여론조사와 관련한 자세한 내용은 중앙선거관리위원회 중앙선거여론조사심의위원회 홈페이지(www.nesdc.go.kr) 참조.


### lexrank 이용한 요약

In [103]:
for summary in summaries:
    print(summary)

,반면 3위 홍 후보는 ‘돼지발정제’ 논란에도 전주(9.5%) 대비 1.5%포인트 상승한 11.0%였습니다
,4위 정의당 심상정 후보는 1.6%포인트 상승한 5.1%, 5위 바른정당 유승민 후보는 0.8%포인트 상승한 4.2%였습니다.,연령별 지지율은 차이가 있었는데요


### space bar 기준 요약

In [104]:
for i in test_index:
    print(test_article_list[i])

[ 동아 일보] ,22 ~28 일 중앙선거관리 위원회 중앙선거 여론조사 심의 위원회에 등록된 여론조사 중 전국 단위, 5 자구도 질문을 포함한 11건의 여론조사를 종합 분석해 평균치를 낸 결과입니다.,
※ 한국 리서치( 내일신문), 리서치 앤 리서치, 한국사회 여론 연구소, 칸 타 코리아, 조원 씨 앤 아이, 메트릭스 코퍼 레이션, 알 앤 써 치, 한국 리서치( 한국 일보· 코리아 타임즈), 리얼 미터, 한국 리서치 (JTBC ·25 일 조사), 한국 리서치 (JTBC ·26 일 조사) 자료 종합, 문 후보의 평균 지지율은 40.4% 로 전주 (42.5%) 대비 2.1% 포인트 하락한 1위였는데요. ,2 위 안 후보의 지지율은 30% 선이 무너졌습니다.
특히 한국 리서치( 한국 일보· 코리아 타임즈) 여론조사에서는 심 후보의 19~29 세 지지율이 17.8% 로 안 후보 (16.7% )를 제치고 2위를 차지하기도 했죠.,


### twitter 사전 이용한 요약 + 전체적으로 빈도수 높은 단어에 가중치

In [105]:
for i in doc_test_index:
    print(test_article_list[i])

※ 한국 리서치( 내일신문), 리서치 앤 리서치, 한국사회 여론 연구소, 칸 타 코리아, 조원 씨 앤 아이, 메트릭스 코퍼 레이션, 알 앤 써 치, 한국 리서치( 한국 일보· 코리아 타임즈), 리얼 미터, 한국 리서치 (JTBC ·25 일 조사), 한국 리서치 (JTBC ·26 일 조사) 자료 종합, 문 후보의 평균 지지율은 40.4% 로 전주 (42.5%) 대비 2.1% 포인트 하락한 1위였는데요. ,2 위 안 후보의 지지율은 30% 선이 무너졌습니다.
위 간 지지율 격차는 12.1% 포인트 차. 전주 (9.7%) 대비 2.4% 포인트 더 벌어졌습니다. ,
특히 한국 리서치( 한국 일보· 코리아 타임즈) 여론조사에서는 심 후보의 19~29 세 지지율이 17.8% 로 안 후보 (16.7% )를 제치고 2위를 차지하기도 했죠.,


### twitter 사전을 이용한 요약 + 전체적으로 빈도수 높은 단어에 가중치 + 제목에 가중치

In [106]:
for i in total_test_index:
    print(test_article_list[i])

※ 한국 리서치( 내일신문), 리서치 앤 리서치, 한국사회 여론 연구소, 칸 타 코리아, 조원 씨 앤 아이, 메트릭스 코퍼 레이션, 알 앤 써 치, 한국 리서치( 한국 일보· 코리아 타임즈), 리얼 미터, 한국 리서치 (JTBC ·25 일 조사), 한국 리서치 (JTBC ·26 일 조사) 자료 종합, 문 후보의 평균 지지율은 40.4% 로 전주 (42.5%) 대비 2.1% 포인트 하락한 1위였는데요. ,2 위 안 후보의 지지율은 30% 선이 무너졌습니다.
위 간 지지율 격차는 12.1% 포인트 차. 전주 (9.7%) 대비 2.4% 포인트 더 벌어졌습니다. ,
특히 한국 리서치( 한국 일보· 코리아 타임즈) 여론조사에서는 심 후보의 19~29 세 지지율이 17.8% 로 안 후보 (16.7% )를 제치고 2위를 차지하기도 했죠.,
